config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "vendors/index"
    get "vendors/show"
    get "vendors/approve"
    get "vendors/reject"
    get "vendors/suspend"
    get "vendors/update"
  end
  resources :shipping_methods
  resources :addresses
  resources :payments
  resources :order_items
  resources :orders
  resources :variants
  resources :products
  resources :categories
  resources :vendors
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :parent
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  belongs_to :variant
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/price_history.rb
class PriceHistory < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :vendor
  belongs_to :category
end

app/models/shipping_method.rb
class ShippingMethod < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :user
end

app/controllers/shipping_methods_controller.rb
class ShippingMethodsController < ApplicationController
  before_action :set_shipping_method, only: %i[ show edit update destroy ]

  # GET /shipping_methods or /shipping_methods.json
  def index
    @shipping_methods = ShippingMethod.all
  end

  # GET /shipping_methods/1 or /shipping_methods/1.json
  def show
  end

  # GET /shipping_methods/new
  def new
    @shipping_method = ShippingMethod.new
  end

  # GET /shipping_methods/1/edit
  def edit
  end

  # POST /shipping_methods or /shipping_methods.json
  def create
    @shipping_method = ShippingMethod.new(shipping_method_params)

    respond_to do |format|
      if @shipping_method.save
        format.html { redirect_to @shipping_method, notice: "Shipping method was successfully created." }
        format.json { render :show, status: :created, location: @shipping_method }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shipping_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shipping_methods/1 or /shipping_methods/1.json
  def update
    respond_to do |format|
      if @shipping_method.update(shipping_method_params)
        format.html { redirect_to @shipping_method, notice: "Shipping method was successfully updated." }
        format.json { render :show, status: :ok, location: @shipping_method }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shipping_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipping_methods/1 or /shipping_methods/1.json
  def destroy
    @shipping_method.destroy!

    respond_to do |format|
      format.html { redirect_to shipping_methods_path, status: :see_other, notice: "Shipping method was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipping_method
      @shipping_method = ShippingMethod.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def shipping_method_params
      params.expect(shipping_method: [ :name, :delivery_estimate, :provider ])
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipping_methods_helper.rb
module ShippingMethodsHelper
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/shipping_methods/_form.html.erb
<%= form_with(model: shipping_method, class: "contents") do |form| %>
  <% if shipping_method.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(shipping_method.errors.count, "error") %> prohibited this shipping_method from being saved:</h2>

      <ul class="list-disc ml-6">
        <% shipping_method.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shipping_method.errors[:name].none?, "border-red-400 focus:outline-red-600": shipping_method.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :delivery_estimate %>
    <%= form.text_field :delivery_estimate, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shipping_method.errors[:delivery_estimate].none?, "border-red-400 focus:outline-red-600": shipping_method.errors[:delivery_estimate].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :provider %>
    <%= form.number_field :provider, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": shipping_method.errors[:provider].none?, "border-red-400 focus:outline-red-600": shipping_method.errors[:provider].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/shipping_methods/_shipping_method.html.erb
<div id="<%= dom_id shipping_method %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= shipping_method.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Delivery estimate:</strong>
    <%= shipping_method.delivery_estimate %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Provider:</strong>
    <%= shipping_method.provider %>
  </div>
</div>

app/views/shipping_methods/edit.html.erb
<% content_for :title, "Editing shipping method" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing shipping method</h1>

  <%= render "form", shipping_method: @shipping_method %>

  <%= link_to "Show this shipping method", @shipping_method, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to shipping methods", shipping_methods_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/shipping_methods/index.html.erb
<% content_for :title, "Shipping methods" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Shipping methods</h1>
    <%= link_to "New shipping method", new_shipping_method_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="shipping_methods" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @shipping_methods.any? %>
      <% @shipping_methods.each do |shipping_method| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render shipping_method %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", shipping_method, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_shipping_method_path(shipping_method), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", shipping_method, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No shipping methods found.</p>
    <% end %>
  </div>
</div>

app/views/shipping_methods/new.html.erb
<% content_for :title, "New shipping method" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New shipping method</h1>

  <%= render "form", shipping_method: @shipping_method %>

  <%= link_to "Back to shipping methods", shipping_methods_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/shipping_methods/show.html.erb
<% content_for :title, "Showing shipping method" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing shipping method</h1>

  <%= render @shipping_method %>

  <%= link_to "Edit this shipping method", edit_shipping_method_path(@shipping_method), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to shipping methods", shipping_methods_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this shipping method", @shipping_method, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>