config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "vendors/index"
    get "vendors/show"
    get "vendors/approve"
    get "vendors/reject"
    get "vendors/suspend"
    get "vendors/update"
  end
  resources :shipping_methods
  resources :addresses
  resources :payments
  resources :order_items
  resources :orders
  resources :variants
  resources :products
  resources :categories
  resources :vendors
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :parent
end

app/models/inventory_adjustment.rb
class InventoryAdjustment < ApplicationRecord
  belongs_to :product
  belongs_to :variant
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  belongs_to :variant
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/price_history.rb
class PriceHistory < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :vendor
  belongs_to :category
end

app/models/shipping_method.rb
class ShippingMethod < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :user
end

app/controllers/admin/vendors_controller.rb
class Admin::VendorsController < ApplicationController
  def index
  end

  def show
  end

  def approve
  end

  def reject
  end

  def suspend
  end

  def update
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: %i[ show edit update destroy ]

  # GET /vendors or /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1 or /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors or /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: "Vendor was successfully created." }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1 or /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: "Vendor was successfully updated." }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1 or /vendors/1.json
  def destroy
    @vendor.destroy!

    respond_to do |format|
      format.html { redirect_to vendors_path, status: :see_other, notice: "Vendor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def vendor_params
      params.expect(vendor: [ :user_id, :business_name, :description, :phone_number, :tax_id, :status, :commission_rate ])
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/vendors_helper.rb
module Admin::VendorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/admin/vendors/approve.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Vendors#approve</h1>
  <p>Find me in app/views/admin/vendors/approve.html.erb</p>
</div>

app/views/admin/vendors/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Vendors#index</h1>
  <p>Find me in app/views/admin/vendors/index.html.erb</p>
</div>

app/views/admin/vendors/reject.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Vendors#reject</h1>
  <p>Find me in app/views/admin/vendors/reject.html.erb</p>
</div>

app/views/admin/vendors/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Vendors#show</h1>
  <p>Find me in app/views/admin/vendors/show.html.erb</p>
</div>

app/views/admin/vendors/suspend.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Vendors#suspend</h1>
  <p>Find me in app/views/admin/vendors/suspend.html.erb</p>
</div>

app/views/admin/vendors/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Vendors#update</h1>
  <p>Find me in app/views/admin/vendors/update.html.erb</p>
</div>

app/views/vendors/_form.html.erb
<%= form_with(model: vendor, class: "contents") do |form| %>
  <% if vendor.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul class="list-disc ml-6">
        <% vendor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": vendor.errors[:user_id].none?, "border-red-400 focus:outline-red-600": vendor.errors[:user_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :business_name %>
    <%= form.text_field :business_name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": vendor.errors[:business_name].none?, "border-red-400 focus:outline-red-600": vendor.errors[:business_name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.textarea :description, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": vendor.errors[:description].none?, "border-red-400 focus:outline-red-600": vendor.errors[:description].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": vendor.errors[:phone_number].none?, "border-red-400 focus:outline-red-600": vendor.errors[:phone_number].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :tax_id %>
    <%= form.text_field :tax_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": vendor.errors[:tax_id].none?, "border-red-400 focus:outline-red-600": vendor.errors[:tax_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.number_field :status, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": vendor.errors[:status].none?, "border-red-400 focus:outline-red-600": vendor.errors[:status].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :commission_rate %>
    <%= form.text_field :commission_rate, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": vendor.errors[:commission_rate].none?, "border-red-400 focus:outline-red-600": vendor.errors[:commission_rate].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/vendors/_vendor.html.erb
<div id="<%= dom_id vendor %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">User:</strong>
    <%= vendor.user_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Business name:</strong>
    <%= vendor.business_name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Description:</strong>
    <%= vendor.description %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Phone number:</strong>
    <%= vendor.phone_number %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Tax:</strong>
    <%= vendor.tax_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Status:</strong>
    <%= vendor.status %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Commission rate:</strong>
    <%= vendor.commission_rate %>
  </div>
</div>

app/views/vendors/edit.html.erb
<% content_for :title, "Editing vendor" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing vendor</h1>

  <%= render "form", vendor: @vendor %>

  <%= link_to "Show this vendor", @vendor, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to vendors", vendors_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/vendors/index.html.erb
<% content_for :title, "Vendors" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Vendors</h1>
    <%= link_to "New vendor", new_vendor_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="vendors" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @vendors.any? %>
      <% @vendors.each do |vendor| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render vendor %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", vendor, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_vendor_path(vendor), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", vendor, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No vendors found.</p>
    <% end %>
  </div>
</div>

app/views/vendors/new.html.erb
<% content_for :title, "New vendor" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New vendor</h1>

  <%= render "form", vendor: @vendor %>

  <%= link_to "Back to vendors", vendors_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/vendors/show.html.erb
<% content_for :title, "Showing vendor" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing vendor</h1>

  <%= render @vendor %>

  <%= link_to "Edit this vendor", edit_vendor_path(@vendor), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to vendors", vendors_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this vendor", @vendor, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>